[versions]
agp = "8.13.1"
kotlin = "2.2.21"

androidx-core-ktx = "1.17.0"
androidx-core-splashscreen = "1.2.0"

junit = "4.13.2"
androidx-junit = "1.3.0"
androidx-espresso-core = "3.7.0"

androidx-lifecycle = "2.10.0"
androidx-activity = "1.12.0"
androidx-navigation = "2.9.6"
androidx-compose-bom = "2025.11.01"

kotlinx-serialization-json = "1.9.0"
kotlinx-coroutines-android = "1.10.2"

cn-lunar = "1.7.7"
com-squareup-okhttp3 = "5.3.2"
com-squareup-okio = "3.16.4"
io-coil-kt-coil3 = "3.3.0"
org-commonmark = "0.27.0"
io-github-carguo-gsyvideoplayer = "11.2.0"

desugar-jdk-libs = "2.1.5"
protolite-well-known-types = "18.0.1"


[libraries]
androidx-core-ktx = {  module = "androidx.core:core-ktx", version.ref = "androidx-core-ktx" }
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "androidx-core-splashscreen" }

junit = {  module = "junit:junit", version.ref = "junit" }
androidx-junit = {  module = "androidx.test.ext:junit", version.ref = "androidx-junit" }
androidx-espresso-core = {  module = "androidx.test.espresso:espresso-core", version.ref = "androidx-espresso-core" }

androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtime-ktx = {  module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidx-lifecycle" }
androidx-activity-compose = {  module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "androidx-navigation" }

androidx-compose-bom = {  module = "androidx.compose:compose-bom", version.ref = "androidx-compose-bom" }
androidx-compose-ui = {  module = "androidx.compose.ui:ui" }
androidx-compose-ui-graphics = {  module = "androidx.compose.ui:ui-graphics" }
androidx-compose-ui-tooling = {  module = "androidx.compose.ui:ui-tooling" }
androidx-compose-ui-tooling-preview = {  module = "androidx.compose.ui:ui-tooling-preview" }
androidx-compose-ui-test-manifest = {  module = "androidx.compose.ui:ui-test-manifest" }
androidx-compose-ui-test-junit4 = {  module = "androidx.compose.ui:ui-test-junit4" }
androidx-compose-material3 = {  module = "androidx.compose.material3:material3" }
androidx-compose-foundation = { module = "androidx.compose.foundation:foundation" }
androidx-compose-animation = { module = "androidx.compose.animation:animation" }

kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization-json" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines-android" }

cn-lunar = { module = "cn.6tail:lunar", version.ref = "cn-lunar" }
io-github-carguo-gsyvideoplayer = { module = "io.github.carguo:gsyvideoplayer", version.ref = "io-github-carguo-gsyvideoplayer" }

com-squareup-okhttp3 = { module = "com.squareup.okhttp3:okhttp", version.ref = "com-squareup-okhttp3" }
com-squareup-okio = { module = "com.squareup.okio:okio", version.ref = "com-squareup-okio" }

io-coil3-coil = { module = "io.coil-kt.coil3:coil", version.ref = "io-coil-kt-coil3" }
io-coil3-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "io-coil-kt-coil3" }
io-coil3-network-okhttp = { module = "io.coil-kt.coil3:coil-network-okhttp", version.ref = "io-coil-kt-coil3" }

org-commonmark = { module = "org.commonmark:commonmark", version.ref = "org-commonmark" }
org-commonmark-ext-image = { module = "org.commonmark:commonmark-ext-image-attributes", version.ref = "org-commonmark" }
org-commonmark-ext-autolink = { module = "org.commonmark:commonmark-ext-autolink", version.ref = "org-commonmark" }
org-commonmark-ext-footnotes = { module = "org.commonmark:commonmark-ext-footnotes", version.ref = "org-commonmark" }
org-commonmark-ext-ins = { module = "org.commonmark:commonmark-ext-ins", version.ref = "org-commonmark" }
org-commonmark-ext-strikethrough = { module = "org.commonmark:commonmark-ext-gfm-strikethrough", version.ref = "org-commonmark" }
org-commonmark-ext-tables = { module = "org.commonmark:commonmark-ext-gfm-tables", version.ref = "org-commonmark" }
org-commonmark-ext-tasklist = { module = "org.commonmark:commonmark-ext-task-list-items", version.ref = "org-commonmark" }

desugar-jdk-libs = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar-jdk-libs" }
protolite-well-known-types = { group = "com.google.firebase", name = "protolite-well-known-types", version.ref = "protolite-well-known-types" }


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

